export interface FontPreset {
  id: string
  name: string
  description: string
  category: 'classic' | 'modern' | 'romantic' | 'royal' | 'minimal' | 'vintage'
  script: string
  display: string
  elegant: string
  body: string
  scriptFallback: string
  displayFallback: string
  elegantFallback: string
  bodyFallback: string
  preview: string
}

export const FONT_PRESETS: FontPreset[] = [
  // ====== CLASSIC (6) ======
  {
    id: 'classic-elegance',
    name: 'Classic Elegance',
    description: 'Great Vibes + Cormorant Garamond',
    category: 'classic',
    script: 'Great Vibes',
    display: 'Cormorant Garamond',
    elegant: 'Cormorant Garamond',
    body: 'Jost',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'timeless-serif',
    name: 'Timeless Serif',
    description: 'EB Garamond klasik',
    category: 'classic',
    script: 'Pinyon Script',
    display: 'EB Garamond',
    elegant: 'EB Garamond',
    body: 'Libre Baskerville',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'vintage-charm',
    name: 'Vintage Charm',
    description: 'Tangerine + Crimson Text',
    category: 'vintage',
    script: 'Tangerine',
    display: 'Crimson Text',
    elegant: 'Crimson Text',
    body: 'Work Sans',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'prata-luxury',
    name: 'Prata Luxury',
    description: 'Prata didone elegan',
    category: 'classic',
    script: 'Monsieur La Doulaise',
    display: 'Prata',
    elegant: 'Cormorant',
    body: 'Raleway',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'bodoni-chic',
    name: 'Bodoni Chic',
    description: 'Bodoni Moda fashion',
    category: 'classic',
    script: 'Rochester',
    display: 'Bodoni Moda',
    elegant: 'Cormorant Garamond',
    body: 'Montserrat',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'libre-caslon',
    name: 'Libre Caslon',
    description: 'Caslon klasik Inggris',
    category: 'classic',
    script: 'Ephesis',
    display: 'Libre Caslon Text',
    elegant: 'Libre Caslon Text',
    body: 'Karla',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },

  // ====== ROMANTIC (6) ======
  {
    id: 'romantic-script',
    name: 'Romantic Script',
    description: 'Parisienne + Lora',
    category: 'romantic',
    script: 'Parisienne',
    display: 'Lora',
    elegant: 'Lora',
    body: 'Karla',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'sacramento-dream',
    name: 'Sacramento Dream',
    description: 'Sacramento ringan manis',
    category: 'romantic',
    script: 'Sacramento',
    display: 'Gelasio',
    elegant: 'Gelasio',
    body: 'Nunito',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'allura-grace',
    name: 'Allura Grace',
    description: 'Allura feminin anggun',
    category: 'romantic',
    script: 'Allura',
    display: 'Marcellus',
    elegant: 'Marcellus',
    body: 'Josefin Sans',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'alex-brush',
    name: 'Alex Brush',
    description: 'Alex Brush dinamis',
    category: 'romantic',
    script: 'Alex Brush',
    display: 'Playfair Display',
    elegant: 'Cormorant',
    body: 'Mulish',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'lavishly-yours',
    name: 'Lavishly Yours',
    description: 'Lavishly romantis bold',
    category: 'romantic',
    script: 'Lavishly Yours',
    display: 'DM Serif Display',
    elegant: 'Cormorant Garamond',
    body: 'Lato',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'mea-culpa',
    name: 'Mea Culpa',
    description: 'Mea Culpa kaligrafi indah',
    category: 'romantic',
    script: 'Mea Culpa',
    display: 'Cormorant Infant',
    elegant: 'Cormorant Infant',
    body: 'Outfit',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },

  // ====== ROYAL (4) ======
  {
    id: 'royal-classic',
    name: 'Royal Classic',
    description: 'Cinzel + EB Garamond',
    category: 'royal',
    script: 'Tangerine',
    display: 'Cinzel',
    elegant: 'EB Garamond',
    body: 'Raleway',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'cinzel-decorative',
    name: 'Cinzel Decorative',
    description: 'Cinzel Decorative megah',
    category: 'royal',
    script: 'Pinyon Script',
    display: 'Cinzel Decorative',
    elegant: 'Cormorant Garamond',
    body: 'Jost',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'italiana-luxe',
    name: 'Italiana Luxe',
    description: 'Italiana mewah Italia',
    category: 'royal',
    script: 'Corinthia',
    display: 'Italiana',
    elegant: 'Josefin Sans',
    body: 'Josefin Sans',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'sans-serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'elsie-royal',
    name: 'Elsie Royal',
    description: 'Elsie dekoratif royal',
    category: 'royal',
    script: 'Monsieur La Doulaise',
    display: 'Elsie',
    elegant: 'Cormorant',
    body: 'Montserrat',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },

  // ====== MODERN (6) ======
  {
    id: 'modern-luxury',
    name: 'Modern Luxury',
    description: 'Playfair + Montserrat',
    category: 'modern',
    script: 'Pinyon Script',
    display: 'Playfair Display',
    elegant: 'Cormorant',
    body: 'Montserrat',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'contemporary',
    name: 'Contemporary',
    description: 'Poppins + Quicksand',
    category: 'modern',
    script: 'Dancing Script',
    display: 'Poppins',
    elegant: 'Quicksand',
    body: 'Quicksand',
    scriptFallback: 'cursive',
    displayFallback: 'sans-serif',
    elegantFallback: 'sans-serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'urban-chic',
    name: 'Urban Chic',
    description: 'Manrope modern clean',
    category: 'modern',
    script: 'Kaushan Script',
    display: 'Manrope',
    elegant: 'Manrope',
    body: 'Manrope',
    scriptFallback: 'cursive',
    displayFallback: 'sans-serif',
    elegantFallback: 'sans-serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'outfit-fresh',
    name: 'Outfit Fresh',
    description: 'Outfit geometris fresh',
    category: 'modern',
    script: 'Yellowtail',
    display: 'Outfit',
    elegant: 'Outfit',
    body: 'Outfit',
    scriptFallback: 'cursive',
    displayFallback: 'sans-serif',
    elegantFallback: 'sans-serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'inter-clean',
    name: 'Inter Clean',
    description: 'Inter netral profesional',
    category: 'modern',
    script: 'Pacifico',
    display: 'Inter',
    elegant: 'Inter',
    body: 'Inter',
    scriptFallback: 'cursive',
    displayFallback: 'sans-serif',
    elegantFallback: 'sans-serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'sora-modern',
    name: 'Sora Modern',
    description: 'Sora futuristik',
    category: 'modern',
    script: 'Dancing Script',
    display: 'Sora',
    elegant: 'Sora',
    body: 'Sora',
    scriptFallback: 'cursive',
    displayFallback: 'sans-serif',
    elegantFallback: 'sans-serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },

  // ====== MINIMAL (4) ======
  {
    id: 'luxe-minimal',
    name: 'Luxe Minimal',
    description: 'Italiana + Josefin',
    category: 'minimal',
    script: 'Allura',
    display: 'Italiana',
    elegant: 'Josefin Sans',
    body: 'Josefin Sans',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'sans-serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'marcellus-pure',
    name: 'Marcellus Pure',
    description: 'Marcellus klasik minimalis',
    category: 'minimal',
    script: 'Alex Brush',
    display: 'Marcellus',
    elegant: 'Marcellus',
    body: 'Nunito Sans',
    scriptFallback: 'cursive',
    displayFallback: 'serif',
    elegantFallback: 'serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'jost-light',
    name: 'Jost Light',
    description: 'Jost ringan geometris',
    category: 'minimal',
    script: 'Great Vibes',
    display: 'Jost',
    elegant: 'Jost',
    body: 'Jost',
    scriptFallback: 'cursive',
    displayFallback: 'sans-serif',
    elegantFallback: 'sans-serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
  {
    id: 'quicksand-soft',
    name: 'Quicksand Soft',
    description: 'Quicksand lembut rounded',
    category: 'minimal',
    script: 'Sacramento',
    display: 'Quicksand',
    elegant: 'Quicksand',
    body: 'Quicksand',
    scriptFallback: 'cursive',
    displayFallback: 'sans-serif',
    elegantFallback: 'sans-serif',
    bodyFallback: 'sans-serif',
    preview: 'Aurelia & Arjuna',
  },
]

export const FONT_CATEGORIES = [
  { id: 'all', name: 'Semua' },
  { id: 'classic', name: 'Classic' },
  { id: 'romantic', name: 'Romantic' },
  { id: 'royal', name: 'Royal' },
  { id: 'modern', name: 'Modern' },
  { id: 'minimal', name: 'Minimal' },
  { id: 'vintage', name: 'Vintage' },
]

export function getFontPresetById(id: string): FontPreset {
  return FONT_PRESETS.find((f) => f.id === id) || FONT_PRESETS[0]
}

export function getFontVariables(presetId: string): Record<string, string> {
  const preset = getFontPresetById(presetId)

  return {
    '--font-script': `'${preset.script}', ${preset.scriptFallback}`,
    '--font-display': `'${preset.display}', ${preset.displayFallback}`,
    '--font-elegant': `'${preset.elegant}', ${preset.elegantFallback}`,
    '--font-body': `'${preset.body}', ${preset.bodyFallback}`,
  }
}

// Load fonts untuk preset tertentu
export function getGoogleFontsUrl(presetIds: string[] = []): string {
  const presets = presetIds.length > 0
    ? FONT_PRESETS.filter((p) => presetIds.includes(p.id))
    : FONT_PRESETS

  const fontFamilies = new Set<string>()

  presets.forEach((preset) => {
    fontFamilies.add(`${preset.script.replace(/ /g, '+')}:wght@400`)
    fontFamilies.add(`${preset.display.replace(/ /g, '+')}:wght@400;500;600;700`)
    fontFamilies.add(`${preset.elegant.replace(/ /g, '+')}:ital,wght@0,400;0,500;1,400`)
    fontFamilies.add(`${preset.body.replace(/ /g, '+')}:wght@300;400;500;600`)
  })

  return `https://fonts.googleapis.com/css2?${Array.from(fontFamilies)
    .map((f) => `family=${f}`)
    .join('&')}&display=swap`
}
